/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RoleManager } from "./RoleManager";
export type { RoleObserver } from "./RoleObserver";
export type { UserManager } from "./UserManager";
