/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as utils from "./utils";
export type { utils };
export type { RoleManager } from "./RoleManager";
export type { RoleObserver } from "./RoleObserver";
export type { UserManager } from "./UserManager";
