/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface TokenFactoryInterface extends utils.Interface {
  functions: {
    "ACTIVE()": FunctionFragment;
    "SUSPENDED()": FunctionFragment;
    "addNewRoleManager(address)": FunctionFragment;
    "addRole(string)": FunctionFragment;
    "createCollection(string,string,string,string)": FunctionFragment;
    "deleteRole(string)": FunctionFragment;
    "initialize()": FunctionFragment;
    "metaTxName()": FunctionFragment;
    "mintShares(address,uint256,string,string,uint256,string,string,string)": FunctionFragment;
    "setRoles(bytes32[])": FunctionFragment;
    "set_MetaTransaction(address)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ACTIVE"
      | "SUSPENDED"
      | "addNewRoleManager"
      | "addRole"
      | "createCollection"
      | "deleteRole"
      | "initialize"
      | "metaTxName"
      | "mintShares"
      | "setRoles"
      | "set_MetaTransaction"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "ACTIVE", values?: undefined): string;
  encodeFunctionData(functionFragment: "SUSPENDED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addNewRoleManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addRole",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createCollection",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteRole",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "metaTxName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mintShares",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setRoles",
    values: [PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "set_MetaTransaction",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ACTIVE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SUSPENDED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addNewRoleManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCollection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "metaTxName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRoles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "set_MetaTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "collectionCreated(address)": EventFragment;
    "sharesMinted(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "collectionCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "sharesMinted"): EventFragment;
}

export interface collectionCreatedEventObject {
  collectionAddress: string;
}
export type collectionCreatedEvent = TypedEvent<
  [string],
  collectionCreatedEventObject
>;

export type collectionCreatedEventFilter =
  TypedEventFilter<collectionCreatedEvent>;

export interface sharesMintedEventObject {
  sharesAddress: string;
}
export type sharesMintedEvent = TypedEvent<[string], sharesMintedEventObject>;

export type sharesMintedEventFilter = TypedEventFilter<sharesMintedEvent>;

export interface TokenFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokenFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ACTIVE(overrides?: CallOverrides): Promise<[string]>;

    SUSPENDED(overrides?: CallOverrides): Promise<[string]>;

    addNewRoleManager(
      newRoleManagerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addRole(
      roleName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createCollection(
      collectionUri: PromiseOrValue<string>,
      collectionName: PromiseOrValue<string>,
      collectionImageURL: PromiseOrValue<string>,
      artistName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deleteRole(
      roleName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaTxName(overrides?: CallOverrides): Promise<[string]>;

    mintShares(
      erc1155address: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      tokenName: PromiseOrValue<string>,
      tokenType: PromiseOrValue<string>,
      priceUSDT: PromiseOrValue<BigNumberish>,
      tokenDescription: PromiseOrValue<string>,
      tokenImageURL: PromiseOrValue<string>,
      tokenURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRoles(
      allAccountRoles: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    set_MetaTransaction(
      metaTxAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[string]>;
  };

  ACTIVE(overrides?: CallOverrides): Promise<string>;

  SUSPENDED(overrides?: CallOverrides): Promise<string>;

  addNewRoleManager(
    newRoleManagerAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addRole(
    roleName: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createCollection(
    collectionUri: PromiseOrValue<string>,
    collectionName: PromiseOrValue<string>,
    collectionImageURL: PromiseOrValue<string>,
    artistName: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deleteRole(
    roleName: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  initialize(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaTxName(overrides?: CallOverrides): Promise<string>;

  mintShares(
    erc1155address: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    tokenName: PromiseOrValue<string>,
    tokenType: PromiseOrValue<string>,
    priceUSDT: PromiseOrValue<BigNumberish>,
    tokenDescription: PromiseOrValue<string>,
    tokenImageURL: PromiseOrValue<string>,
    tokenURI: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRoles(
    allAccountRoles: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  set_MetaTransaction(
    metaTxAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    ACTIVE(overrides?: CallOverrides): Promise<string>;

    SUSPENDED(overrides?: CallOverrides): Promise<string>;

    addNewRoleManager(
      newRoleManagerAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addRole(
      roleName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    createCollection(
      collectionUri: PromiseOrValue<string>,
      collectionName: PromiseOrValue<string>,
      collectionImageURL: PromiseOrValue<string>,
      artistName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteRole(
      roleName: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(overrides?: CallOverrides): Promise<void>;

    metaTxName(overrides?: CallOverrides): Promise<string>;

    mintShares(
      erc1155address: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      tokenName: PromiseOrValue<string>,
      tokenType: PromiseOrValue<string>,
      priceUSDT: PromiseOrValue<BigNumberish>,
      tokenDescription: PromiseOrValue<string>,
      tokenImageURL: PromiseOrValue<string>,
      tokenURI: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRoles(
      allAccountRoles: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    set_MetaTransaction(
      metaTxAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "collectionCreated(address)"(
      collectionAddress?: PromiseOrValue<string> | null
    ): collectionCreatedEventFilter;
    collectionCreated(
      collectionAddress?: PromiseOrValue<string> | null
    ): collectionCreatedEventFilter;

    "sharesMinted(address)"(
      sharesAddress?: PromiseOrValue<string> | null
    ): sharesMintedEventFilter;
    sharesMinted(
      sharesAddress?: PromiseOrValue<string> | null
    ): sharesMintedEventFilter;
  };

  estimateGas: {
    ACTIVE(overrides?: CallOverrides): Promise<BigNumber>;

    SUSPENDED(overrides?: CallOverrides): Promise<BigNumber>;

    addNewRoleManager(
      newRoleManagerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addRole(
      roleName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createCollection(
      collectionUri: PromiseOrValue<string>,
      collectionName: PromiseOrValue<string>,
      collectionImageURL: PromiseOrValue<string>,
      artistName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deleteRole(
      roleName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaTxName(overrides?: CallOverrides): Promise<BigNumber>;

    mintShares(
      erc1155address: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      tokenName: PromiseOrValue<string>,
      tokenType: PromiseOrValue<string>,
      priceUSDT: PromiseOrValue<BigNumberish>,
      tokenDescription: PromiseOrValue<string>,
      tokenImageURL: PromiseOrValue<string>,
      tokenURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRoles(
      allAccountRoles: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    set_MetaTransaction(
      metaTxAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ACTIVE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SUSPENDED(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addNewRoleManager(
      newRoleManagerAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addRole(
      roleName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createCollection(
      collectionUri: PromiseOrValue<string>,
      collectionName: PromiseOrValue<string>,
      collectionImageURL: PromiseOrValue<string>,
      artistName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deleteRole(
      roleName: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaTxName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mintShares(
      erc1155address: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      tokenName: PromiseOrValue<string>,
      tokenType: PromiseOrValue<string>,
      priceUSDT: PromiseOrValue<BigNumberish>,
      tokenDescription: PromiseOrValue<string>,
      tokenImageURL: PromiseOrValue<string>,
      tokenURI: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRoles(
      allAccountRoles: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    set_MetaTransaction(
      metaTxAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
