/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface TokenShopInterface extends utils.Interface {
  functions: {
    "buyTokensWithMatic(uint256,address,uint256)": FunctionFragment;
    "buyTokensWithUSDT(uint256,address,uint256)": FunctionFragment;
    "claimTokensAfterFiatPayment(uint256,address,uint256)": FunctionFragment;
    "metaTxName()": FunctionFragment;
    "set_MetaTransaction(address)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyTokensWithMatic"
      | "buyTokensWithUSDT"
      | "claimTokensAfterFiatPayment"
      | "metaTxName"
      | "set_MetaTransaction"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyTokensWithMatic",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buyTokensWithUSDT",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTokensAfterFiatPayment",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "metaTxName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "set_MetaTransaction",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "buyTokensWithMatic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyTokensWithUSDT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTokensAfterFiatPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "metaTxName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "set_MetaTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "tokensBought(address,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "tokensBought"): EventFragment;
}

export interface tokensBoughtEventObject {
  tokenAddress: string;
  tokenId: BigNumber;
  buyer: string;
}
export type tokensBoughtEvent = TypedEvent<
  [string, BigNumber, string],
  tokensBoughtEventObject
>;

export type tokensBoughtEventFilter = TypedEventFilter<tokensBoughtEvent>;

export interface TokenShop extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokenShopInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyTokensWithMatic(
      amountToBuy: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    buyTokensWithUSDT(
      amountToBuy: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimTokensAfterFiatPayment(
      amountToClaim: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    metaTxName(overrides?: CallOverrides): Promise<[string]>;

    set_MetaTransaction(
      metaTxAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[string]>;
  };

  buyTokensWithMatic(
    amountToBuy: PromiseOrValue<BigNumberish>,
    tokensAddress: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  buyTokensWithUSDT(
    amountToBuy: PromiseOrValue<BigNumberish>,
    tokensAddress: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimTokensAfterFiatPayment(
    amountToClaim: PromiseOrValue<BigNumberish>,
    tokensAddress: PromiseOrValue<string>,
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  metaTxName(overrides?: CallOverrides): Promise<string>;

  set_MetaTransaction(
    metaTxAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    buyTokensWithMatic(
      amountToBuy: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    buyTokensWithUSDT(
      amountToBuy: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    claimTokensAfterFiatPayment(
      amountToClaim: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    metaTxName(overrides?: CallOverrides): Promise<string>;

    set_MetaTransaction(
      metaTxAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "tokensBought(address,uint256,address)"(
      tokenAddress?: null,
      tokenId?: null,
      buyer?: null
    ): tokensBoughtEventFilter;
    tokensBought(
      tokenAddress?: null,
      tokenId?: null,
      buyer?: null
    ): tokensBoughtEventFilter;
  };

  estimateGas: {
    buyTokensWithMatic(
      amountToBuy: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    buyTokensWithUSDT(
      amountToBuy: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimTokensAfterFiatPayment(
      amountToClaim: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    metaTxName(overrides?: CallOverrides): Promise<BigNumber>;

    set_MetaTransaction(
      metaTxAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    buyTokensWithMatic(
      amountToBuy: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    buyTokensWithUSDT(
      amountToBuy: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimTokensAfterFiatPayment(
      amountToClaim: PromiseOrValue<BigNumberish>,
      tokensAddress: PromiseOrValue<string>,
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    metaTxName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    set_MetaTransaction(
      metaTxAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
