/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CustomERC20__factory } from "./CustomERC20__factory";
export { ERC1155Contract__factory } from "./ERC1155Contract__factory";
