/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20SharesGenerator } from "./ERC20SharesGenerator";
export type { ERC721Generator } from "./ERC721Generator";
